import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Basic',
  description: 'Generated by create next app',
};

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function BasicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main
      className={cn(
        'font-sans antialiased p-8 bg-gradient-to-br from-yellow-200 via-green-200 to-green-300',
        fontSans.variable
      )}
    >
      {children}
    </main>
  );
}
