import { Modal } from '@/components/faceted/Modal';
import PokeballSvg from '@/components/icons/PokeballSvg';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import '../globals.css';
import MyPokemon from './components/MyPokemon';

export const metadata: Metadata = {
  title: 'Basic',
  description: 'Generated by create next app',
};

export default function BasicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main
      className={cn(
        'font-sans antialiased p-8 bg-gradient-to-br from-yellow-200 via-green-200 to-green-300'
      )}
    >
      <div className="absolute right-8 top-8">
        <Modal
          trigger={<PokeballSvg width={50} height={50} />}
          title="My Pokemon"
        >
          <MyPokemon />
        </Modal>
      </div>
      {children}
    </main>
  );
}
